# Run unit tests using CTest
name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run unit tests
      uses: HorstBaerbel/action-ctest@1.1
      with:
          submodules: recursive
      # These are optional (defaults displayed)
      with:
        sourcedir: '.'
        builddir: 'build'
        cmakeoptions: '--config Release'
        ctestoptions: ''
